<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Carrito.aspx.cs" Inherits="Vistas.WebForm2" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <style type="text/css">
        .auto-style1 {
            margin-bottom: 0px;
        }
        .auto-style2 {
            width: 100%;
        }
        .auto-style3 {
            height: 26px;
        }
        </style>
</head>
<body style="margin: 50px 200px;">
    <form id="form1" runat="server">
        <div>
            <table class="auto-style2" style="align-content:center;border: 3px solid black">
                <tr>
                    <td style="text-align:left">
            <asp:HyperLink ID="HyperLink1" runat="server" NavigateUrl="~/HomeUsuario.aspx">Volver al Inicio</asp:HyperLink>
                    </td>
                    <td style="text-align:center">CARRITO DE COMPRAS</td>
                    <td style="text-align:right">
                        <asp:Label ID="LblUsuario" runat="server"></asp:Label>
                    </td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td colspan="3" style="text-align: center">
            <asp:GridView ID="GrdCarrito" runat="server" AutoGenerateDeleteButton="True" OnRowDeleting="GrdCarrito_RowDeleting" AutoGenerateColumns="False" HorizontalAlign="Center">
                <Columns>
                    <asp:TemplateField HeaderText="ID Carrito" Visible="False">
                        <ItemTemplate>
                            <asp:Label ID="LblCarrito" runat="server" Text='<%# Bind("CodCarrito") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="ID Artículo">
                        <ItemTemplate>
                            <asp:Label ID="LblArticulo" runat="server" Text='<%# Bind("CodArticulo") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Descripción">
                        <ItemTemplate>
                            <asp:Label ID="LblDescripcion" runat="server" Text='<%# Bind("Descripcion") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Precio">
                        <ItemTemplate>
                            <asp:Label ID="LblPrecio" runat="server" Text='<%# Bind("Precio") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Cantidad">
                        <ItemTemplate>
                            <asp:TextBox ID="TxtCantidad" runat="server" CssClass="auto-style1" Text='<%# Bind("Cantidad") %>'></asp:TextBox>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Sub Total">
                        <ItemTemplate>
                            <asp:Label ID="LblSubtotal" runat="server" Text='<%# Bind("SubTotal") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>
                    </td>
                </tr>
                <tr>
                    <td class="auto-style3"></td>
                    <td class="auto-style3"></td>
                    <td class="auto-style3"></td>
                </tr>
                <tr style="text-align:left">
                    <td colspan="3">
            <asp:Button ID="BtnActualizar" runat="server" OnClick="BtnActualizar_Click" Text="Actualizar tabla" />
                    &nbsp;<asp:Button ID="BtnComprar" runat="server" Text="Realizar compra" OnClick="BtnComprar_Click" />
                    &nbsp;Total a pagar: $ <asp:Label ID="LblTotal" runat="server"></asp:Label>
                    </td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td colspan="3">
            <asp:Label ID="LblCompra" runat="server"></asp:Label>
            <asp:Label ID="LblError" runat="server"></asp:Label>
                    </td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
            </table>
            <br />
        </div>
    </form>
</body>
</html>
