<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Carrito.aspx.cs" Inherits="Vistas.WebForm2" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <style type="text/css">
        .auto-style1 {
            margin-bottom: 0px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            Carrito
            <asp:HyperLink ID="HyperLink1" runat="server" NavigateUrl="~/HomeUsuario.aspx">Volver</asp:HyperLink>
            <br />
            <br />
            <asp:GridView ID="GrdCarrito" runat="server" AutoGenerateDeleteButton="True" OnRowDeleting="GrdCarrito_RowDeleting" AutoGenerateColumns="False">
                <Columns>
                    <asp:TemplateField HeaderText="ID Carrito" Visible="False">
                        <ItemTemplate>
                            <asp:Label ID="LblCarrito" runat="server" Text='<%# Bind("CodCarrito") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="ID Artículo">
                        <ItemTemplate>
                            <asp:Label ID="LblArticulo" runat="server" Text='<%# Bind("CodArticulo") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Descripción">
                        <ItemTemplate>
                            <asp:Label ID="LblDescripcion" runat="server" Text='<%# Bind("Descripcion") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Precio">
                        <ItemTemplate>
                            <asp:Label ID="LblPrecio" runat="server" Text='<%# Bind("Precio") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Cantidad">
                        <ItemTemplate>
                            <asp:TextBox ID="TxtCantidad" runat="server" CssClass="auto-style1" Text='<%# Bind("Cantidad") %>'></asp:TextBox>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Sub Total">
                        <ItemTemplate>
                            <asp:Label ID="LblSubtotal" runat="server" Text='<%# Bind("SubTotal") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>
            <br />
            Total a pagar: $ <asp:Label ID="LblTotal" runat="server"></asp:Label>
            <br />
            <br />
            <asp:Button ID="BtnActualizar" runat="server" OnClick="BtnActualizar_Click" Text="Actualizar tabla" />
            <br />
        </div>
    </form>
</body>
</html>
